### ISSUE TITLE
Unable to get fluid absorber to work

### ISSUE THREAD

**Issue by Avalonzo** [benbenlaw-modpacks/Techopolis-2#19]
in your latest build I'm unable to get fluid absorbers to work with their new smaller size or did their size get changed by mistake I have tried flowing and source blocks.

![2023-04-03_16 18 45](https://user-images.githubusercontent.com/8142543/229555018-0211d9fe-d3c3-475e-9e0e-d8ccec566827.png)

![2023-04-03_16 18 55](https://user-images.githubusercontent.com/8142543/229555093-95599446-5cc4-47ab-b504-d439465e0ede.png)

![2023-04-03_16 18 35](https://user-images.githubusercontent.com/8142543/229555153-6d32624e-6bf6-470c-9d0a-f945524c7fa3.png)

Also cannot get it to work with the original size.

![2023-04-03_16 38 03](https://user-images.githubusercontent.com/8142543/229559286-e8ea284f-42f1-468e-8f3a-6085e7ad3674.png)

**Comment by Avalonzo** [comment]
Worked it out the cauldron isn't considered as a valid tank once I stuck a fluid trashcan on top it started working then removing it and placing the cauldron back on top stops it from working.

**Comment by damionisaloser** [comment]
I havent been able to get it to work either i even got to thermal and used a fluid cell and the sounds are working but it still doesnt output any

**Comment by Avalonzo** [comment]
> I havent been able to get it to work either i even got to thermal and used a fluid cell and the sounds are working but it still doesnt output any

Oh really when I put the fluid trash can on top and heard the noise I just assumed it was working will see if can get working.

**Comment by Avalonzo** [comment]
I got mine working with an immersive pump on top doesn't need power then setting a side to output then using immersive pipes.
