### ISSUE TITLE
how to use crafting automat

### ISSUE THREAD

**Issue by Apishrana** [benbenlaw-modpacks/Techopolis-2#20]
when i was using crafting automat to craft compressed coblestone it is not crafting it and it voids the compressed coblestone

![2023-04-04](https://user-images.githubusercontent.com/96068620/229752841-ff285749-cf36-4d3d-bab6-db9c1fec420d.png)

**Comment by Avalonzo** [comment]
From what I can tell these have been removed in the latest version of the pack B3

**Comment by Apishrana** [comment]
ok
i will update it now
