### ISSUE TITLE
soaked paper craft is not a shapeless craft?

### ISSUE THREAD

**Issue by Blackness744** [benbenlaw-modpacks/Techopolis-2#24]
been trying to find a way to get soaked paper craft to work with a ceramic bucket but the craft is only allowing normal buckets (iron). tested it on 2 different worlds (noticed on survival tested on creative). only way that allows me to get the craft is if i cheat and get an (iron) bucket by going to creative then back to survival. any ideas or am I just dumb?

**Comment by benbenlaw** [comment]
fixed in B5.0
