### ISSUE TITLE
Tree Absorber Doesn't Auto Load Into Drawer Controller Slave

### ISSUE THREAD

**Issue by HumdrumPanic** [benbenlaw-modpacks/Techopolis-2#71]
Tree Absorber Doesn't Auto Load Into Storage Drawer's Drawer Controller Slave like it would with a vanilla barrel or chest.

This could be true for all miners/absorbers but I noticed it with the Tree Absorber.

Build Tree absorber with frames - tree (I used standard oak) - dirt block and the tree absorber block itself. Place barrel under the tree absorber block. Confirmed Absorber is working and loading into barrel. 

Replace barrel with Drawer controller slave - linked with drawer trim to 1x1 drawers locked with Leaves, sticks, logs, and apples and a Drawer Controller to complete Storage Drawer setup. Confirm slave and drawers and trim are all within the modpack's default range (50 blocks, normally 12 I think) of the Drawer Controller.

After confirming all of that, the Absorber doesn't insert into the Slave Controller resulting in the 1x1 storage drawers inventory increasing as the tree absorber mines.

**Comment by BondarenkoArtur** [comment]
Mine works fine
![image](https://github.com/bbl-team/Techopolis-2/assets/9720950/0b4cd76e-6035-42e5-a594-c4c474f94c04)

**Comment by HumdrumPanic** [comment]
Mine works now as well... I dunno what I did different... maybe it just needed a restart
