### ISSUE TITLE
Weathered Copper Blocks Don't Give Miner Cap Bonus Speed

### ISSUE THREAD

**Issue by HumdrumPanic** [benbenlaw-modpacks/Techopolis-2#72]
Not sure if intentional or simple oversight for the skyblock version. 

The copper blocks as miner caps no longer work (No longer give speed boosts to miners) once they become weathered/oxidized/exposed ect. I have not tested if the waxed variants are the same.

**Comment by LeSwede** [comment]
They do if you wax them to prevent oxidizing. But that requires a honey comb.

**Comment by HumdrumPanic** [comment]
Ok cool, I haven't gotten that far yet, to access honey comb. At least I think(On the skyblock version). I mean I progressed past the copper block miner cap pretty quickly anyways, but It still may be an oversight unless:

The modpack team may have allowed this intentionally as a "Haha you should have gone with tin instead" sorta thing. I'll leave this issue open until they confirm/close it if that's the case.

**Comment by HumdrumPanic** [comment]
Ah I missed this bit.  Seems to be a multi block issue... I'll close this now

![image](https://github.com/bbl-team/Techopolis-2/assets/64377875/ba6da471-9964-456b-bceb-77efcd2eac54)
