### ISSUE TITLE
When i break colored stone with my Prospector Pickaxe i cant seem to get fragments.

### ISSUE THREAD

**Issue by Broutsteak** [benbenlaw-modpacks/Techopolis-2#73]
Whenever i seem to break the colored stone with the prospector pickaxe it just drops the colored stone instead of the resorces (Coal and lapis in this situation)

**Comment by HumdrumPanic** [comment]
Did you accidentally click the quest to turn off the fragment generation?
 
![image](https://github.com/bbl-team/Techopolis-2/assets/64377875/cf67a8d9-99d9-4ff5-8b75-47727ff96ecd)

**Comment by Broutsteak** [comment]
I did not

**Comment by Broutsteak** [comment]
But i turned on commands to try to manually turn it on and the command doesnt show up, so that might be it. but idk

/gamestage add @p coal_and_lapis. but coal_and_lapis is missing.

**Comment by HumdrumPanic** [comment]
Sorry that was all I had for a quick fix its beyond me now. You'll have to wait for someone with more knowledge about /gamestage  or someone from the modpack team

They might need more info though. like if it ever worked or if it just all of a sudden stopped working and if so when, if you can tell that is... something they can use to reproduce the bug

**Comment by Broutsteak** [comment]
Yea no worries imma just wait or reinstall the pack, also i havent been able to get a single coal or lapis fragment, like it just never worked.

**Comment by HumdrumPanic** [comment]
Which colored stone? The one the quest book leads you to? Light Gray Colored Stone?
![image](https://github.com/bbl-team/Techopolis-2/assets/64377875/66239cd7-c62f-461a-920e-41e0ced6cad1)

**Comment by Broutsteak** [comment]
The quest book leads me to light grey yea

**Comment by Broutsteak** [comment]
Ok now it works lol, just had to restart the game. Thanks anyway

**Comment by Broutsteak** [comment]
Just had to restart the game and it worked.
