### ISSUE TITLE
Is there a way to make new Islands for new People who join the server

### ISSUE THREAD

**Issue by Smurx** [benbenlaw-modpacks/Techopolis-2#75]
Is there a way to give someone a new island if they join or for them to use a command to do that?

In older skyblock-modpacks there seemed to be a way with ftb i think but im am not to sure how to do it in this one.

**Comment by HumdrumPanic** [comment]
This isn't really what this github is for... you'll be better off on the discord:  https://discord.gg/7aZtcKbJ

Don't forget to close this issue

**Comment by Smurx** [comment]
Oh ok thx xD would have asked on diwcord but all the linkes didnt work
